apiVersion: v1
kind: Service
metadata:
  name: flask-service #The name of the Kubernetes Service to be created in the Kubernetes cluster
  namespace: flask-project
spec:
  selector:
    app: flask-app
  type: NodePort #Type of the Kubernetes Service
  ports:
    - protocol: TCP
      port: 5000 #Service port
      targetPort: 5000 #The port for the React.js application container
      nodePort: 32222
